kind: Deployment
apiVersion: apps/v1
metadata:
  name: envoy
  namespace: envoy
  labels:
    name: envoy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: envoy
  template:
    metadata:
      labels:
        name: envoy
    spec:
      volumes:
        - name: config
          configMap:
            name: config
            defaultMode: 420
            optional: false
        - name: certs
          secret:
            secretName: certs
            defaultMode: 420
            optional: false
      containers:
        - name: envoy-sidecar
          image: 'envoyproxy/envoy:v1.16.0'
          args:
            - '-c'
            - /config/envoy.yaml
            - '-l'
            - debug
          ports:
            - name: envoy
              containerPort: 10000
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /config
              mountPropagation: None
            - name: certs
              mountPath: /certs
              mountPropagation: None
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10

