apiVersion: v1
kind: Service
metadata:
  labels:
    name: envoy-cl2
  name: envoy-cl2
  namespace: envoy
spec:
  ports:
  - name: envoy-cl2
    port: 10003
    protocol: TCP
    targetPort: 10003
  selector:
    name: envoy
  sessionAffinity: None
  type: ClusterIP
