apiVersion: v1
kind: Service
metadata:
  labels:
    name: envoy-cl1
  name: envoy-cl1
  namespace: envoy
spec:
  ports:
  - name: envoy-cl1
    port: 10002
    protocol: TCP
    targetPort: 10002
  selector:
    name: envoy
  sessionAffinity: None
  type: ClusterIP
